# Source: https://github.com/krlmlr/r-appveyor/blob/master/appveyor.yml

# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  - ps: |
      $ErrorActionPreference = "Stop"
      Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
      Import-Module '..\appveyor-tool.ps1'
install:
  - ps: Bootstrap
  - git submodule update --init --recursive

environment:
  app_version: "1.2.0"
  USE_RTOOLS: true
  R_VERSION: "4.1.0"
  R_ARCH: x64
  KEEP_VIGNETTES: true
  NOT_CRAN: true

version: "$(app_version).{build}"

platform: x64

skip_commits:
  files:
    - "*.md"

skip_branch_with_pr: true

skip_tags: true

branches:
  only:
    - develop

pull_requests:
  do_not_increment_build_number: true

before_test:
  - cinst pandoc
  - ps: $env:Path += ";C:\Program Files (x86)\Pandoc\"
  - pandoc -v

build_script:
  - travis-tool.sh install_deps
  - travis-tool.sh r_binary_install curl
  - Rscript -e "install.packages('covr', repos = 'http://cran.us.r-project.org', type = 'source')"

test_script:
  - travis-tool.sh run_tests

on_success:
  - Rscript -e "covr::codecov()"

after_test:
  - ps: copy ospsuite.utils_*.zip ospsuite.utils.zip

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: 'ospsuite.utils*.zip'
    name: Bits
